(function(){
  const copy={
    ko:{intro:'소개',support:'지원',privacy:'개인정보',kicker:'PRIVATE COLLECTION COMPANION',hero:'최애를<br>한 권에<br>모아요.',body:'내 포토카드 사진, 보유·위시·교환 상태와 덕질비를 계정 없이 기기 안에서 정리하세요.',look:'기능 살펴보기',why:'COLLECTION, YOUR WAY',whyTitle:'수집의 설렘은 남기고<br>정리의 부담은 줄였어요.',photo:'내 사진으로 기록',photoBody:'내가 가진 포토카드 사진과 그룹·멤버·카드명을 직접 기록합니다.',status:'상태가 보이는 바인더',statusBody:'전체·보유·위시·교환 필터와 검색으로 원하는 카드를 바로 찾습니다.',offline:'개인적인 로컬 보관',offlineBody:'계정과 개발자 서버 없이 핵심 데이터가 내 기기에 남습니다.',real:'실제 실행 화면',pay:'기본은 무료, Pro는 한 번 구매',payBody:'무료로 카드를 30장까지 추가할 수 있습니다. Pro를 한 번 구매하면 새 카드를 무제한으로 추가할 수 있고, 기존 카드와 백업은 계속 이용할 수 있습니다.',policy:'개인정보처리방침'},
    en:{intro:'Intro',support:'Support',privacy:'Privacy',kicker:'PRIVATE COLLECTION COMPANION',hero:'Your bias.<br>One beautiful<br>binder.',body:'Organize your photocard photos, owned, wish and trade status, and fandom spending on your device without an account.',look:'Explore features',why:'COLLECTION, YOUR WAY',whyTitle:'Keep the joy of collecting.<br>Lose the organizing stress.',photo:'Record your own cards',photoBody:'Add your own photocard photos, group, member, and card names.',status:'A binder that shows status',statusBody:'Find any card with search and all, owned, wish, or trade filters.',offline:'Private local storage',offlineBody:'Core data stays on your device without an account or developer server.',real:'Real app screens',pay:'Free basics, one-time Pro',payBody:'Add up to 30 cards for free. One Pro purchase unlocks unlimited new card additions, while existing cards and backups remain available.',policy:'Privacy policy'},
    ja:{intro:'紹介',support:'サポート',privacy:'プライバシー',kicker:'PRIVATE COLLECTION COMPANION',hero:'大切な推しを<br>一冊の<br>バインダーに。',body:'トレカ写真、所持・ウィッシュ・交換の状態、推し活費をアカウントなしで端末内に整理できます。',look:'機能を見る',why:'COLLECTION, YOUR WAY',whyTitle:'集める楽しさはそのまま。<br>整理の負担はもっと軽く。',photo:'自分の写真で記録',photoBody:'自分のトレカ写真、グループ、メンバー、カード名を登録します。',status:'状態が見えるバインダー',statusBody:'検索と、すべて・所持・ウィッシュ・交換フィルターですぐに見つかります。',offline:'プライベートな端末内保存',offlineBody:'アカウントや開発者サーバーを使わず、主要データは端末に残ります。',real:'実際のアプリ画面',pay:'基本無料、Proは買い切り',payBody:'無料で30枚まで追加できます。Proを一度購入すると新しいカードを無制限に追加でき、既存カードとバックアップは引き続き利用できます。',policy:'プライバシーポリシー'}
  };
  function apply(lang){const c=copy[lang]||copy.en;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=c[el.dataset.i18n];if(v)el.innerHTML=v});document.querySelector('[data-language]').value=lang;localStorage.setItem('biasBinderLanguage',lang)}
  const select=document.querySelector('[data-language]');if(select)select.addEventListener('change',e=>apply(e.target.value));const saved=localStorage.getItem('biasBinderLanguage');const guessed=(navigator.language||'en').slice(0,2);apply(saved||(['ko','en','ja'].includes(guessed)?guessed:'en'));
})();
